"""
Trains the TF-IDF + Logistic Regression disruption classifier.

Usage:
    python -m app.ml.classification.train

Data source: backend/data/synthetic_articles.csv (generated by
scripts/generate_synthetic_data.py from the taxonomy + real
merged_supply_chain_data.xlsx keywords/summaries), or any CSV with
columns [text, label].
"""
import os
import sys
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from app.ml.classification.model import DisruptionClassifierModel

DATA_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "..", "data", "synthetic_articles.csv")


def main():
    df = pd.read_csv(DATA_PATH)
    df = df.dropna(subset=["text", "label"])

    # Drop classes with too few examples to stratify-split (keeps training robust
    # on small/early-stage datasets rather than crashing).
    counts = df["label"].value_counts()
    df = df[df["label"].isin(counts[counts >= 2].index)]

    le = LabelEncoder()
    y = le.fit_transform(df["label"])
    stratify = y if counts.min() >= 2 else None
    X_train, X_test, y_train, y_test = train_test_split(df["text"], y, test_size=0.2, random_state=42, stratify=stratify)

    pipeline = Pipeline([
        ("tfidf", TfidfVectorizer(max_features=5000, ngram_range=(1, 2), stop_words="english")),
        ("clf", LogisticRegression(max_iter=1000, class_weight="balanced")),
    ])
    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)
    labels_present = sorted(set(y_test) | set(y_pred))
    print(classification_report(
        y_test, y_pred,
        labels=labels_present,
        target_names=[le.classes_[i] for i in labels_present],
        zero_division=0,
    ))

    model = DisruptionClassifierModel(pipeline, le)
    model.save()
    print("Model saved to app/ml/classification/artifacts/disruption_clf.joblib")


if __name__ == "__main__":
    sys.exit(main())
